Project group cypress tests
DFE-Digital/prepare-academy-conversions pull request #1170
Opened 2024-08-27 09:42 UTC by FahadDarw

This test will create a conversion then it will test groups.

2024-08-27 09:50 UTC, cshnimble requested changes

2024-08-27 09:50 UTC, cshnimble commented on Dfe.PrepareConversions/Dfe.PrepareConversions.CypressTests/cypress/pages/projectTaskList.js
> +    static path1 = 'groups/project-list'
Can this have a more descriptive name please?

2024-08-27 09:50 UTC, cshnimble commented on Dfe.PrepareConversions/Dfe.PrepareConversions.CypressTests/cypress/pages/projectTaskList.js
> +        confirmandcontinue: '[data-cy="select-common-submitbutton"]'
needs to use lower camel case like other variable names for consistency

2024-08-27 09:50 UTC, cshnimble commented on Dfe.PrepareConversions/Dfe.PrepareConversions.CypressTests/cypress/pages/projectTaskList.js
> +        cy.get('[data-cy="tes"]').click();
I know it's not been added in this PR, but is this data-cy tag named well?

2024-08-27 09:50 UTC, cshnimble commented on Dfe.PrepareConversions/Dfe.PrepareConversions.CypressTests/cypress/e2e/Core-journeys/project_group_test.cy.js
> +describe('Decisions Tests', () => {
Are these still decisions tests?

2024-08-27 09:50 UTC, cshnimble commented on Dfe.PrepareConversions/Dfe.PrepareConversions.CypressTests/cypress/e2e/Core-journeys/project_group_test.cy.js
> +    Logger.log("enerting which trust will the group join");
entering?

2024-08-28 15:57 UTC, cshnimble approved these changes

2024-08-29 08:16 UTC, mshakirdfe approved these changes

2025-02-10 16:17 UTC, closed without merging