refactored trust guidance to separate pages for sponsored
DFE-Digital/prepare-academy-conversions pull request #763
Opened 2023-05-05 15:04 UTC by dneed-nimble

2023-05-05 15:07 UTC, dneed-nimble commented on Dfe.PrepareConversions/Dfe.PrepareConversions/Pages/TaskList/TrustTemplate/TrustTemplateGuidance.cshtml
> +@if (@Model.Project.IsSponsored)
I'd rather just have separate pages, but the ticket specified wanting one url slug for both entry points i.e., Voluntary or Sponsored

2023-05-05 16:11 UTC, paullocknimble approved these changes

2023-05-09 10:25 UTC, chrisdexnimble requested changes
I think the tag helper is fine. Just commented on one of the warnings

2023-05-09 12:48 UTC, chrisdexnimble approved these changes

2023-05-09 13:27 UTC, merged