model discrepancy bug fix plus update to unit test
DFE-Digital/prepare-academy-conversions pull request #820
Opened 2023-06-21 10:40 UTC by danielryannimble

bux fix and unit test update

2023-06-21 14:06 UTC, dneed-nimble requested changes
The changes that are needed is to remove the opening date and shift our reliance to the proposed academy opening date, both UI and API side. This will have implications across the system. In templates and all models (post, update and search) etc.

We should probably close this PR and revisit.

2023-06-23 11:15 UTC, danielryannimble commented on Dfe.PrepareConversions/Dfe.PrepareConversions.Tests/Pages/TaskList/SchoolAndTrustInformation/ProposedAcademyOpeningDateIntegrationTests.cs
> +
good spot after chat with dom ive put the test back to how it was!

2023-06-26 12:54 UTC, dneed-nimble commented on release-notes.md
> +* Bugfix 132060 : the opening date will be populated with the ProposedAcadamenyOpeningDate value
Could you follow convention with the naming here, this is also incorrect as they opening date will not be populated as you have removed it! haha

2023-06-26 14:45 UTC, dneed-nimble approved these changes

2023-06-26 14:51 UTC, merged